# what a module is ? 

# basiclly it's a file that has predefined
# function that u can use by importin the module
# or just importing a function form it . 


# how to import a module : 

import random 

# how to import all functions in a modules :

from random import *

# how to import a spacefic function : '

from random import randint 

# what are the fuctions inside a module : 

print(dir(random))

# printing a random intger by randint :

print(randint(100 , 200)) # range 100 to 200



